services:
  tor:
    build: .
    container_name: proxyforge-tor
    restart: unless-stopped
    networks:
      - proxy_net
    ports:
      - "1080:9050"   # SOCKS standard mapped to Tor internal

  privoxy:
    image: vimagick/privoxy
    container_name: proxyforge-http
    restart: unless-stopped
    depends_on:
      - tor
    networks:
      - proxy_net
    ports:
      - "8080:8118"   # HTTP standard mapped to Privoxy internal
    volumes:
      - ./privoxy/config:/etc/privoxy

networks:
  proxy_net: